default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

joint_limits:
  rarm_joint_1:
    has_velocity_limits: true
    max_velocity: 3.2288591161895095
    has_acceleration_limits: true
    max_acceleration: 17.453292519943297
  rarm_joint_2:
    has_velocity_limits: true
    max_velocity: 3.2288591161895095
    has_acceleration_limits: true
    max_acceleration: 15.707963267948966
  rarm_joint_3:
    has_velocity_limits: true
    max_velocity: 3.7000980142279785
    has_acceleration_limits: true
    max_acceleration: 23.56194490192345
  rarm_joint_4:
    has_velocity_limits: true
    max_velocity: 8.377580409572781
    has_acceleration_limits: true
    max_acceleration: 52.35987755982988
  rarm_joint_5:
    has_velocity_limits: true
    max_velocity: 7.190756518216638
    has_acceleration_limits: true
    max_acceleration: 36.65191429188092
  rarm_joint_6:
    has_velocity_limits: true
    max_velocity: 12.304571226560023
    has_acceleration_limits: true
    max_acceleration: 80.28514559173917
  larm_joint_1:
    has_velocity_limits: true
    max_velocity: 3.2288591161895095
    has_acceleration_limits: true
    max_acceleration: 17.453292519943297
  larm_joint_2:
    has_velocity_limits: true
    max_velocity: 3.2288591161895095
    has_acceleration_limits: true
    max_acceleration: 15.707963267948966
  larm_joint_3:
    has_velocity_limits: true
    max_velocity: 3.7000980142279785
    has_acceleration_limits: true
    max_acceleration: 23.56194490192345
  larm_joint_4:
    has_velocity_limits: true
    max_velocity: 8.377580409572781
    has_acceleration_limits: true
    max_acceleration: 52.35987755982988
  larm_joint_5:
    has_velocity_limits: true
    max_velocity: 7.190756518216638
    has_acceleration_limits: true
    max_acceleration: 36.65191429188092
  larm_joint_6:
    has_velocity_limits: true
    max_velocity: 12.304571226560023
    has_acceleration_limits: true
    max_acceleration: 80.28514559173917
